### PR TITLE
Bump Rx versions - Fixes #5

### LINKED ISSUE #5: Update RxJS and RxJS-DOM
Need to get to latest version of these.

### PR DESCRIPTION
**Pull request by jmalonzo**

### CODE REVIEW

**Comment by jmalonzo** [comment]
Hi @blesh just wondering if there's anything else stopping this from being merged?

Thanks.

**Comment by blesh** [comment]
@jmalonzo it can't be merged at the moment because the [tests are failing on your branch](https://travis-ci.org/blesh/RxSocketSubject/builds/70850082)

**Comment by jmalonzo** [comment]
@blesh Thanks. FYI - I believe the tests started failing prior to 0.6.4 (c5afc54) - https://travis-ci.org/blesh/RxSocketSubject/builds.

I'll see if I can figure out how to fix it.

**Comment by jmalonzo** [comment]
@blesh I'm not sure exactly why the test was updated to check for returnValue as that doesn't seem to be available in the testem/jasmine version bundled in package.json (i.e. I don't get the `returnValue` prop when I run it locally).

I've removed that check for now. Let me know if that satisfies you.

**Comment by blesh** [comment]
Hmm... the test failures are strange. I'm unsure how that came about, I'll have to investigate. Yeah, this will be fine. Thank you @jmalonzo

**Pull request merged**
