### PR TITLE
Update Rx and build deps

### PR DESCRIPTION
**Pull request by jmalonzo**
Hi @blesh,

I've updated the Rx deps as I think there aren't really big breaking changes happening there that will break this project. And there are more upsides to it as, for example, the projects who depend on this project can at least grab the latest Rx(-DOM).

I've also updated the build deps and fixed the tests in the process. Also, it would be nice to have a patch release to refresh the bower version :-)

What do you think?

### CODE REVIEW

**Comment by jmalonzo** [comment]
No worries. I've pinned the Rx version to 3.1.1 and -DOM to 6.0.

**Comment by jmalonzo** [comment]
@blesh just updated the patch to Rx 4.0. Tests are fine. Any chance of getting this merged and tagged?

Thanks.

**Comment by blesh** [comment]
Sure. The weekend is rough, though. If you don't hear back from me by Tuesday, please comment again in this issue. I'll try to review Monday morning, though.

**Comment by jmalonzo** [comment]
No worries, will do. Thanks a lot!

**Comment by jmalonzo** [comment]
*bump*

**Comment by blesh** [comment]
HA! Good thing I told you to remind me.

**Comment by blesh** [comment]
All merged, thanks @jmalonzo

**Comment by jmalonzo** [comment]
No worries @blesh. Thanks for the merge. Mind if we get a new tagged release to go with it too? :)

Cheers

**Comment by blesh** [comment]
@jmalonzo done. `0.7.0` since the RxJS dependency has breaking changes.

**Comment by jmalonzo** [comment]
Thanks a lot @blesh. Have a good weekend!

**Pull request merged**
